### ISSUE TITLE
Method to return `Cookie` with cookie content and helper to return user and password

### ISSUE THREAD

**Issue by RCasatta** [RCasatta/bitcoind#55]
There are clients like [lightningd](https://github.com/RCasatta/lightningd) that accept user and password as parameter, they could read the file content via `bitcoind.params.cookie_file` but it would be easier with a struct `Cookie` returned from `BitcoinD::cookie()` on which one could call `user()` and `password()`

**Comment by oleonardolima** [comment]
@RCasatta I was looking at this one and was curious: does it need a `Cookie` struct ?

Would the idea be for it to have the original `.cookie` content or just the user and password fields ?

I'm asking because it could have a method that uses (or acts as)  [`bitcoincore-rpc::Auth::get_user_pass`](https://docs.rs/bitcoincore-rpc/0.16.0/bitcoincore_rpc/enum.Auth.html#method.get_user_pass) and already returns user and password 🤔

**Comment by RCasatta** [comment]
It doesn't have to be a `Cookie` struct also a new fn on params returning `Result<(Option<String>, Option<String>)>`  would do the job.

The end goal is to simplify user code like this https://github.com/RCasatta/lightningd/blob/master/src/lib.rs#L64-#L71

**Comment by oleonardolima** [comment]
I've implemented a new method following this approach here #103

I'm wondering why the CI is failing while trying to compile `which`, I guess it's a problem with the `which` crate itself unrelated to the changes 🤔 , but I've not been able to take a look yet.
